services:
  app:
    image: nishindudu/internalbooks:latest
    container_name: internalbooks
    ports:
      - "80:80"
    
    volumes:
      - app_data:/app/data:rw
    working_dir: /app
    entrypoint: ["/app/main.bin"]
    
    restart: unless-stopped

volumes:
  app_data: