const eulaContent = `**END USER LICENSE AGREEMENT (EULA)**

**Last Updated:** June 19, 2025

This End User License Agreement ("EULA") is a legal agreement between you (either an individual or a single entity, hereinafter "Licensee" or "You") and **Nishin Santhosh, Kerala, India** ("Licensor") for the software product identified as **InternalBooks** ("Software"), which includes the software, any associated media, printed materials, and "online" or electronic documentation.

By installing, copying, downloading, accessing, or otherwise using the Software, You agree to be bound by the terms of this EULA. If You do not agree to the terms of this EULA, do not install or use the Software.

**1. DEFINITIONS**
    a. "Software" means the **InternalBooks** application, provided as a Docker-containerized package, including any compiled code, associated data files (excluding Licensee-generated data), templates, static assets, scripts, and documentation.
    b. "Instance" means a single running copy of the Software on a server or virtual machine, identified by a unique **Instance ID** generated by the Software.
    c. "Activation Key" means a unique key provided by Licensor to Licensee **upon purchase of a license**, enabling the generation of a perpetual License Key.
    d. "License Key" means a unique digital key generated by Licensor's servers upon successful validation of a purchased Activation Key and **Instance ID**, which enables the full functionality of the Software for a specific Instance beyond the Trial Period.
    e. "**Instance ID**" means a unique identifier automatically generated by the Software upon its first run within a specific Instance.
    f. "Trial Period" means a period of ten (10) days commencing from the date the Software Instance first successfully communicates with Licensor's activation server using its **Instance ID**, during which the Software may be used with full features for evaluation purposes.

**2. LICENSE GRANT**
    a. **Scope of License:** Subject to the terms and conditions of this EULA and payment of any applicable license fees (unless under a Trial Period), Licensor grants You a non-exclusive, non-transferable (except as expressly permitted herein), limited license to install and use **one (1) Instance** of the Software on a single server controlled by You, solely for Your internal business purposes of tracking income and expenses.
    b. **Activation and Trial:**
        i. Upon initial startup and successful communication with Licensor's activation server using the Software-generated **Instance ID**, the Software will operate under the **Trial Period** with full functionality.
        ii. To continue using the Software with full functionality beyond the Trial Period, You must purchase a license, for which You will receive an **Activation Key**. You must then submit this purchased Activation Key along with the Software's **Instance ID** to Licensor's activation server. Upon successful validation, Licensor will provide a perpetual **License Key** to be stored by the Software. This License Key is specific to the **Instance ID** of the Instance it was activated for and cannot be used for another Instance.
    c. **Term:**
        i. **Purchased License:** The license granted herein upon successful activation with a purchased **Activation Key** is **perpetual** for the specific version of the Software activated at that time, subject to the termination clauses of this EULA. This **perpetual** aspect pertains to the right to use the provided version of the Software indefinitely as delivered. **Licensee acknowledges and agrees that the continued functionality of this specific Software version is dependent on the stability and compatibility of various third-party technologies (including, but not limited to, the Docker platform, the host operating system, web browsers, and underlying software libraries) which are outside of Licensor's control and may change over time. Licensor is under no obligation to provide updates, patches, or modifications to the Software to ensure its continued compatibility with future changes or versions of such third-party technologies. Any such compatibility updates, if ever provided, are at Licensor's sole discretion and may be subject to terms outlined in Section 6.**
        ii. **Trial Period Use:** Use of the Software during the Trial Period is governed by the terms of this EULA, except that it is limited to the duration of the Trial Period and does not require payment of a license fee for that initial period. Upon expiration of the Trial Period, the Software's functionality may be disabled or restricted unless a purchased License Key is obtained and applied.

**3. RESTRICTIONS ON USE**
    You may NOT, directly or indirectly:
    a. Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, underlying ideas, algorithms, file formats, or programming interfaces of the Software in any way, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation. The Software is provided in an obfuscated/compiled format, and any attempts to bypass this are prohibited.
    b. Modify, adapt, translate, or create derivative works based on the Software.
    c. Rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make the Software available to any third party for any reason.
    d. Use the Software for service bureau purposes, software-as-a-service (SaaS) offerings, time-sharing, or otherwise for the benefit of third parties.
    e. Remove or obscure any copyright, trademark, or other proprietary notices from the Software or its documentation.
    f. Use the Software to develop a competing product or service.
    g. Use a single purchased Activation Key (after its initial activation for a specific **Instance ID**) or a single perpetual License Key to activate or run more than one (1) Instance of the Software simultaneously. The Licensor's activation system links a purchased Activation Key to a single **Instance ID** upon successful activation for a perpetual license.
    h. Circumvent or attempt to circumvent any license key, activation, or copy protection mechanisms in the Software, including any Trial Period limitations.
    i. Use the Software for any illegal purpose or in violation of any local, state, national, or international law.

**4. INTELLECTUAL PROPERTY RIGHTS**
    a. The Software is licensed, not sold. Licensor retains all right, title, and interest in and to the Software and any copies thereof, including all copyright, patent, trademark, trade secret, and other intellectual property rights.
    b. All rights not expressly granted to You in this EULA are reserved by Licensor.

**5. FEES AND PAYMENT**
    a. Use of the Software during the Trial Period is free of charge. Continued use of the Software with full functionality beyond the Trial Period requires the purchase of a license, for which You will receive an Activation Key upon payment of the applicable license fee(s) as agreed at the time of purchase. The license granted under this EULA for such continued use is contingent upon this payment.

**6. SUPPORT AND MAINTENANCE**
    a. **Limited Support:** Licensor is under no obligation to provide ongoing support, maintenance, or comprehensive updates for the Software under this EULA.
    b. **Critical Updates:** Licensor may, at its sole discretion, provide updates to address critical security vulnerabilities or major bugs ("Critical Updates") in the then-current version of the Software. However, the provision of any Critical Updates is not guaranteed, does not imply any ongoing commitment to support or update the Software further, **nor does it guarantee compatibility with future changes in underlying operating systems, Docker versions, or other third-party dependencies beyond the scope of the specific Critical Update.**
    c. **No New Features Guaranteed:** This EULA does not entitle You to any new feature releases or major version upgrades unless explicitly offered by Licensor, potentially under new license terms or fees.

**7. DATA AND PRIVACY**
    a. **Licensee Data:** You are solely responsible for all data, information, and material that You create, enter, upload, or manage using the Software ("Licensee Data"), including its legality, reliability, integrity, accuracy, and quality. This may include employee names if You choose to enter them. As the Software is self-hosted, Licensor has no access to Your Licensee Data.
    b. **DATA BACKUP AND RECORD-KEEPING RESPONSIBILITY: LICENSEE ACKNOWLEDGES AND AGREES THAT IT IS SOLELY AND ENTIRELY RESPONSIBLE FOR THE CREATION, MAINTENANCE, REGULAR TESTING, AND SECURE STORAGE OF BACKUPS OF ALL LICENSEE DATA AND THE SOFTWARE INSTANCE CONFIGURATION. THE SOFTWARE IS PROVIDED AS A TOOL TO ASSIST WITH RECORD-KEEPING AND SHOULD NOT BE SOLELY RELIED UPON AS THE SINGLE SOURCE OF TRUTH FOR FINANCIAL OR OTHER CRITICAL DATA. LICENSOR STRONGLY RECOMMENDS THAT LICENSEE MAINTAIN INDEPENDENT PHYSICAL AND/OR DIGITAL RECORDS OF ALL DATA ENTERED INTO THE SOFTWARE. LICENSOR SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY LOSS, CORRUPTION, OR INACCESSIBILITY OF LICENSEE DATA, REGARDLESS OF CAUSE, OR FOR ANY DAMAGES ARISING FROM RELIANCE SOLELY ON THE SOFTWARE FOR RECORD-KEEPING.**
    c. **Activation Data:** During the initial activation for the Trial Period and any subsequent activation for a perpetual license, the Software will transmit its **Instance ID** to Licensor. If a purchased Activation Key is used, it will also be transmitted. Licensor will store this information, along with relevant dates, for the purposes of license validation, managing Trial Periods, support (if any provided), and to prevent unauthorized use.

**8. THIRD-PARTY SOFTWARE AND DATA**
    a. The Software may utilize or include third-party software components or data, which are subject to their own license terms. A list of such components and their respective licenses is available within the Software's documentation or on a designated page within the Software's user interface. Your use of such third-party components is governed by their respective licenses. This EULA does not limit your rights under, or grant you rights that supersede, the license terms of any such third-party components.

**9. DISCLAIMER OF WARRANTIES**
    a. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, OR ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.
    b. LICENSOR DOES NOT WARRANT THAT THE SOFTWARE WILL BE ERROR-FREE, UNINTERRUPTED, SECURE, OR THAT DEFECTS WILL BE CORRECTED. LICENSOR PROVIDES NO GUARANTEE OF ONGOING MAINTENANCE OR SUPPORT BEYOND WHAT IS STATED IN SECTION 6. **LICENSOR SPECIFICALLY DISCLAIMS ANY WARRANTY REGARDING THE SOFTWARE'S CONTINUED COMPATIBILITY OR FUNCTIONALITY WITH FUTURE VERSIONS OR CHANGES TO OPERATING SYSTEMS, DOCKER, WEB BROWSERS, OR OTHER THIRD-PARTY TECHNOLOGIES UPON WHICH ITS OPERATION MAY DEPEND.** YOU ACKNOWLEDGE THAT YOUR USE OF THE SOFTWARE IS AT YOUR SOLE RISK.
    c. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR OR ITS AUTHORIZED REPRESENTATIVES SHALL CREATE A WARRANTY.

**10. LIMITATION OF LIABILITY**
    a. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LICENSOR OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, DATA LOSS OR CORRUPTION, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR ANY OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR INABILITY TO USE THE SOFTWARE, EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
    b. IN NO EVENT SHALL LICENSOR'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES FOR A PURCHASED LICENSE IN ANY ONE OR MORE CAUSES OF ACTION EXCEED THE AMOUNT PAID BY YOU FOR THE SOFTWARE LICENSE. **IF THE SOFTWARE IS USED DURING THE FREE TRIAL PERIOD, OR IS OTHERWISE PROVIDED AT NO COST, LICENSOR'S TOTAL LIABILITY TO YOU SHALL BE NIL (ZERO), TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. WHERE APPLICABLE LAW DOES NOT ALLOW LIABILITY TO BE NIL, LICENSOR'S LIABILITY SHALL BE LIMITED TO THE MINIMUM AMOUNT PERMITTED BY SUCH LAW (E.G., USD $1.00 OR EQUIVALENT).**
    c. The limitations of liability and disclaimers of warranty in this EULA form an essential basis of the bargain between the parties and shall apply even if any limited remedy is found to have failed its essential purpose.

**11. INDEMNIFICATION**
    You agree to indemnify, defend, and hold harmless Licensor from and against any and all claims, losses, damages, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to Your use or misuse of the Software, Your breach of this EULA, or Your violation of any law or the rights of a third party.

**12. TERM AND TERMINATION**
    a. This EULA is effective until terminated.
    b. You may terminate this EULA at any time by destroying all copies of the Software and its documentation.
    c. Without prejudice to any other rights, Licensor may terminate this EULA if You fail to comply with any of its terms and conditions. In such event, You must immediately cease all use of the Software and destroy all copies of the Software and all of its component parts and documentation.
    d. Sections 3, 4, 7, 8, 9, 10, 11, 13, 14, and 15 shall survive any termination of this EULA.

**13. GOVERNING LAW AND JURISDICTION**
    This EULA shall be governed by and construed in accordance with the laws of **India**, without regard to its conflict of law principles. Any legal action or proceeding arising under this EULA will be brought exclusively in the competent courts located in **Kerala, India**, and the parties hereby irrevocably consent to the personal jurisdiction and venue therein. The United Nations Convention on Contracts for the International Sale of Goods shall not apply to this EULA.

**14. EXPORT CONTROLS**
    You agree to comply with all applicable Indian and international export laws and regulations as they apply to the Software. You agree not to export or re-export the Software to any country, person, or entity subject to applicable export restrictions.

**15. GENERAL PROVISIONS**
    a. **Entire Agreement:** This EULA constitutes the entire agreement between You and Licensor relating to the Software and supersedes all prior or contemporaneous oral or written communications, proposals, and representations with respect to the Software or any other subject matter covered by this EULA.
    b. **Severability:** If any provision of this EULA is held to be void, invalid, unenforceable, or illegal, the other provisions shall continue in full force and effect.
    c. **Waiver:** No waiver of any breach of any provision of this EULA shall constitute a waiver of any prior, concurrent, or subsequent breach of the same or any other provisions hereof, and no waiver shall be effective unless made in writing and signed by an authorized representative of the waiving party.
    d. **Notices:** All notices pertaining to this EULA shall be in writing and sent to Licensor at **internalbooks@proton.me** and to Licensee at the address or email provided during purchase or activation, or such other address as either party may designate.
    e. **No Assignment:** You may not assign Your rights or obligations under this EULA without the prior written consent of Licensor. Licensor may assign this EULA without Your consent.

**BY INSTALLING OR USING THE SOFTWARE, YOU ACKNOWLEDGE THAT YOU HAVE READ THIS EULA, UNDERSTAND IT, AND AGREE TO BE BOUND BY ITS TERMS AND CONDITIONS.**

If You have any questions concerning this EULA, or if You desire to contact Licensor for any reason, please write to:
**Nishin Santhosh**
Email: **internalbooks@proton.me**
`


async function renderEULA() {
    const eulaText = document.querySelector('.eula-text');
    // const eulaContent = await fetch('/EULA.md');
    eulaText.innerHTML = marked.parse(eulaContent);
}

renderEULA();

const acceptButton = document.querySelector('#accept-eula');
acceptButton.addEventListener('change', () => {
    const downloadButton = document.querySelector('#dwnldbtn');
    downloadButton.disabled = !acceptButton.checked;
});